---
language: python
python: "2.7"

sudo: required
dist: trusty

env:
  - DB=postgresql
  - DB=sqlite

install:
  # Install Ansible to deploy HaaS
  - pip install ansible
  - ansible-playbook -i hosts site.yml -v -e database=$DB

script:
  # Try to run command
  # sudo is required because of /etc/haas.cfg permissions
  - cd /var/lib/haas && sudo haas-admin db create && sudo haas list_projects
