---
language: python
python: "2.7"

sudo: required
dist: trusty

install:
  # Install Ansible to deploy HaaS
  - pip install ansible
  - ansible-playbook -i hosts site.yml -v

script:
  # Try to run command
  - cd /var/lib/haas
  - haas list_projects

