---
language: python
python: "2.7"

sudo: required
dist: trusty

env:
  - DB=postgresql
  - DB=sqlite

install:
  # Install Ansible to deploy HaaS
  - pip install ansible
  - ansible-playbook -i hosts site.yml -v -e database=$DB

script:
  # Try to run command
  - sudo chmod 777 /etc/haas.cfg && cd /var/lib/haas && haas init_db && haas list_projects

