---
language: python
python: "2.7"

sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get purge -y postgresql-9.1 postgresql-9.2 postgresql-9.3

install:
  # Install Ansible to deploy HaaS
  - pip install ansible
  - ansible-playbook -i hosts site.yml -v

script:
  # Try to run command
  - cd /var/lib/haas
  - haas list_projects

