---
language: python
python: "2.7"

sudo: required
dist: trusty

install:
  # Install Ansible to deploy HaaS
  - pip install ansible
  - ansible-playbook -i hosts site.yml -v

script:
  # Try to run command
  - su haas
  - haas init_db
  - haas list_projects

