---
# IF CentOS / RHEL
- name: disable selinux
  selinux: state=disabled
  when: ansible_os_family == 'RedHat'
# END IF

# IF Ubuntu
- name: update apt-get cache
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'
# END IF

- name: install dependencies CentOS/RHEL
  package: name={{ item }} state=present
  with_items: "{{ dependencies }}"
