---
- name: install epel-release
  yum: name=epel-release state=present
  when: ansible_distribution == "CentOS" or ansible_distribution == 'RedHat'

- name: install epel-release
  yum:
    name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
   - libvirt
   - bridge-utils
   - ipmitool
   - telnet
   - python-pip
   - python-lxml
   - python-devel
   - qemu-kvm
   - virt-install
   - gcc
   - git
   - wget
