---
# IF CentOS/RHEL
- name: install postgres CentOS/RHEL
  yum: name={{ item }} state=present
  with_items:
   - python-psycopg2
   - postgresql-server
   - postgresql-contrib
   - postgresql
  when: ansible_os_family == 'RedHat'
  register: postgres_rhel

- name: init db CentOS/RHEL
  command: postgresql-setup initdb
  when: postgres_rhel.changed and ansible_os_family == 'RedHat'

- name: copy pg_hba.conf RHEL
  copy:
    src=pg_hba.conf
    dest=/var/lib/pgsql/data/pg_hba.conf
  when: postgres_rhel.changed and ansible_os_family == 'RedHat'
# END IF

# IF Ubuntu
- name: install postgres Ubuntu
  apt: name={{ item }} state=present
  with_items:
   - python-psycopg2
   - postgresql
  when: ansible_distribution == 'Ubuntu'
  register: postgres_ubuntu

- name: copy pg_hba.conf Ubuntu
  copy:
    src=pg_hba.conf
    dest=/etc/postgresql/9.*/main/pg_hba.conf
  when: postgres_ubuntu.changed and ansible_distribution == 'Ubuntu'
# END IF

- name: restart postgresql
  service:
    name=postgresql
    state=restarted
    enabled=yes

- name: create db for haas
  become: yes
  become_user: postgres
  postgresql_db: name={{ haas_user }}

- name: create db user for haas
  become: yes
  become_user: postgres
  postgresql_user:
    db={{ haas_user }}
    name={{ haas_user }}
    password={{ haas_pass }}
    priv=CONNECT/ALL
