---
- name: Install apache2, mod_wsgi
  package: name={{ item }} state=present
  with_items:
    - "{{ apache }}"
    - "{{ mod_wsgi }}"

- name: Copy site configuration for apache
  template:
    src=wsgi.conf.{{ ansible_os_family }}.j2
    dest={{ site_conf }}

- name: restart httpd
  service:
    name={{ apache }}
    state=restarted
    enabled=yes

- name: create /var/www/haas
  file:
    path=/var/www/haas/
    state=directory

- name: copy haas.wsgi
  command: cp /var/lib/haas/haas/haas.wsgi /var/www/haas/haas.wsgi
